export const SET_KEY = 'SET_KEY';
export const TRYING_TO_CONNECT_TO_ROOM = 'TRYING_TO_CONNECT_TO_ROOM';
export const CONNECT_SUCCESSFUL = 'CONNECT_SUCCESSFUL';
export const TOGGLE_DEVICE_TYPE = 'TOGGLE_DEVICE_TYPE';
export const SEND_IMAGE_DATA = 'SEND_IMAGE_DATA';

export const CHANGE_ROUTE = 'CHANGE_ROUTE';